export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR';
export const LOAD_MORE_ACCOUNTS_SUCCESS = 'LOAD_MORE_ACCOUNTS_SUCCESS';
export const SORT_ACCOUNT_SUCCESS = 'SORT_ACCOUNT_SUCCESS';

export const GET_INVOICE_REQUEST = 'GET_INVOICE_REQUEST';
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_ERROR = 'GET_INVOICE_ERROR';
export const LOAD_MORE_INVOICE_SUCCESS = 'LOAD_MORE_INVOICE_SUCCESS';
export const SORT_INVOICE_SUCCESS = 'SORT_INVOICE_SUCCESS';